### ISSUE TITLE
The constructor's stepNumber does not use to order the job steps created.

### ISSUE THREAD

**Issue by ChauchaMonte** [Rocket-Buddha/batch-engine#19]
![Screen Shot 2020-01-16 at 11 29 24 AM](https://user-images.githubusercontent.com/20520831/72533188-800d0780-3853-11ea-8692-2f5069bbb810.png)

https://github.com/Rocket-Buddha/batch-engine/blob/0c2dba38a33d5ad41cc5ebc1cace04b11a31263c/lib/core/BatchStep.ts#L65

**Comment by Rocket-Buddha** [comment]
Merged by pull request #20.
